upstash/redis-js

pkg/pipeline.test.ts, pkg/pipeline.ts, pkg/redis.test.ts, pkg/redis.ts
This allows you to more or less use a similar API from the last version:
```ts
import { Redis } from "@upstash/redis"
const { get, set } = new Redis({/* TODO: auth */})
```
=> fix: bind `this` correctly when destructuring `Redis` or `Pipeline`

.github/workflows/tests.yaml
The daily tests were failing because it could not create the same tag
twice.
=> ci: add build time to release tag

pkg/http.ts
In Next.js v13, `fetch` responses are cached, so when a similar request is sent multiple times, the first response is always returned, which is not the intended behavior. Add `cache: 'no-store'` to the `fetch` options to disable unintended caching. Since `cache: 'no-store'` is a standard option, it may work on other platforms as well.
=> fix: set `cache: 'no-store'`

.github/workflows/tests.yaml, examples/netlify-edge/netlify.toml, examples/netlify-edge/netlify/edge-functions/hello.ts, examples/netlify-edge/netlify/edge-functions/incr.ts, examples/netlify-edge/test.ts, platforms/nodejs.ts
- avoid accessing process.version in edge runtime
- refactor(nodejs.ts): reformat Redis class addTelemetry method for better readability
=> telemetry in vercel edge

pkg/commands/copy.test.ts, pkg/commands/copy.ts, pkg/commands/mod.ts, pkg/pipeline.ts, pkg/redis.ts
=> Add copy command to SDK

pkg/script.ts
This ought to fix https://github.com/upstash/upstash-redis/issues/698.
I think, error is related to the way TypeScript and Node.js handle module resolution and imports, particularly in relation to the ECMAScript modules.
When set to bundler, TypeScript is told that the code will be bundled by another tool, so it loosens the rules with imports, allowing imports without file extensions or with `.ts` extensions​. This is especially useful for projects that will be bundled using tools like Webpack, Rollup, or others, as it aligns with the way these tools resolve modules.
However, it's important to note that while TypeScript allows for omitting extensions with the bundler option, Node.js and in-browser JavaScript still expect file extensions to be present for ESM. This is because, in the world …
=> fix: add file extensions

package.json
Fixes #774
`module` field was missing from the `package.json` so `.mjs` files were not chosen
=> DX-531: Add esm to package.json

pkg/commands/geo_search.test.ts, pkg/commands/geo_search.ts, pkg/commands/geo_search_store.test.ts, pkg/commands/geo_search_store.ts
The `COUNT`  (both on GEOSEARCH and GEOSEARCHSTORE) was missing according the official Redis Docs: https://redis.io/commands/geosearch/
I need this change to improve performance on my application with working COUNT Limit.
Before the fix, I got the following error:
```
[UpstashError]: ERR syntax error, command was: ["GEOSEARCH","cache:hotels:geo-index","FROMLONLAT",-8.672491,37.10109,"BYRADIUS",10,"KM","ASC",50]
```
=> Fix GEOSEARCH Command when Limit is set

.github/workflows/release.yml, .github/workflows/tests.yaml
It might be better to use the official `bun` action directly for the workflow.
In this way, we will not need to install the `setup-node` in actions where `npm` is not required. 
Just `bun` may be enough.
=> chore: add setup-bun action to workflows

pkg/commands/expire.ts
Implicit undefined values as the expiry option work, however passing an explicit undefined to our `expire` command is possible on the type-level but leads to a runtime error. This PR allows explicit undefined values by filtering them in our SDK before submitting.
=> fix: filter falsy values before sending request

pkg/commands/hgetall.ts
Closes #1047
`Number.isSafeInteger('50')` returns `false`
`Number.isSafeInteger(50)` returns `true`
=> Fix detection unsafe integer

pkg/auto-pipeline.test.ts, pkg/auto-pipeline.ts, pkg/commands/lmpop.test.ts, pkg/commands/lmpop.ts, pkg/commands/mod.ts, pkg/pipeline.ts, pkg/redis.ts
This PR adds missing LMPOP command.
Fixes #1060
=> feat: add lmpop command

pkg/auto-pipeline.test.ts, pkg/auto-pipeline.ts, pkg/redis.ts, platforms/cloudflare.ts, platforms/fastly.ts, platforms/nodejs.ts
instead of enforcing string values to init Redis, we now accept undefined values and provide a runtime error if the init was not called with actual string values for `url` and `token`.
(unrelated) some files were not formatted, included proper formatting in this pr
=> Allow undefined constructor values

pkg/auto-pipeline.test.ts, pkg/auto-pipeline.ts
Since json commands are called with redis.json.get, redis.json returned the proxy and redis.json.get simply called the json.get of the pipeline of auto pipeline executor.
as response to redis.json.get, we simply returned the pipeline of auto executor with json.get called. This also added a command to the pipeline without incrementing `indexInCurrentPipeline`, essentially corrupting the auto pipeline.
Added a json parameter to `createAutoPipelineProxy`. Returned a json proxy if command is json. Not the cleanest solution but it works.
I feel like we can go over the types in the proxy later on. It looks a bit messy.
=> Fix Auto-pipeline Proxy Json Issue

pkg/commands/geo_search.ts, pkg/commands/hscan.test.ts, pkg/commands/hscan.ts, pkg/commands/scan.test.ts, pkg/commands/scan.ts, pkg/commands/sscan.test.ts, pkg/commands/sscan.ts, pkg/commands/zscan.test.ts, pkg/commands/zscan.ts, pkg/util.ts
scan commands can return a '0' or a long number as a string. If we deserialize, we get 0 from '0' and a truncated number from the long number string. Second one is non-ideal.
In this case, we want to return the cursor as a string. This means excluding the cursor from the deserialization, hence the new deserializeScanResponse method.
Additionally, making the cursor parameter in scan commands `string | number`
=> DX-997: Make cursor field in scan commands string

pkg/http.ts, platforms/cloudflare.ts, platforms/fastly.ts, platforms/nodejs.ts
Adding a parameter to make it possible to set keepAlive to false.
This is needed in our data browser where large requests fail because of a limit when keepAlive is true. [See for more details](https://github.com/getsentry/sentry-javascript/issues/1464).
I tested the browser with keepAlive: false and I was able to set/update large values.
=> feat: add keepAlive parameter

pkg/commands/bitfield.test.ts, pkg/commands/bitfield.ts, pkg/commands/command.ts, pkg/commands/mod.ts, pkg/error.ts, pkg/pipeline.test.ts, pkg/pipeline.ts, pkg/redis.ts
=> feat: add bitfield command

pkg/auto-pipeline.test.ts, pkg/auto-pipeline.ts
when a redis method which is available in .json but not available in the pipeline is used while auto pipeline is enabled, proxy doesn't check properly that the method is a function and attempts to return from pipeline, instead of pipeline.json.
=> Resolve Auto Pipeline Arrappend Issue

pkg/redis.ts
Auto pipelining allows the client to batch requests whenever possible. See [our docs](https://upstash.com/docs/oss/sdks/ts/redis/pipelining/auto-pipeline) to learn more.
This PR enables auto pipelining by default.
=> Enable auto pipelining by default

biome.json, pkg/commands/json_mset.test.ts, pkg/commands/json_mset.ts, pkg/commands/mod.ts, pkg/pipeline.ts, pkg/redis.ts
=> feat: add json mset command

pkg/commands/bitfield.ts
Should fix #1231 by adding the missing name to the tuple type `SubCommandArgs`.
=> Fix TS5084 Error in Bitfield SubCommandArgs

.github/workflows/tests.yaml, .husky/pre-commit
- Remove tests from the pre-commit process.
- Remove the cron job from the GitHub test workflow to avoid flaky test execution. We don't want the large "Tests are failing" tag to appear when a test fails.
=> chore: remove cron from github flow

pkg/read-your-writes.test.ts, pkg/redis.ts
Adds set and get methods for upstashSyncToken used for RYW added in #1175 
```ts
const redis = new Redis(...)
const syncToken = redis.readYourWritesSyncToken;
const newSyncToken = "my-new-sync-token";
redis.readYourWritesSyncToken = newSyncToken;
```
=> Add sync token set/get methods

platforms/nodejs.ts
Add support for directly using @upstash/redis with Vercel KV env variables
=> Accept vercel kv env variables

pkg/auto-pipeline.test.ts, pkg/auto-pipeline.ts, pkg/pipeline.test.ts, pkg/pipeline.ts
Addressing the auto pipeline issue which causes https://github.com/upstash/ratelimit-js/issues/122
Essentially, when one of the commands in the pipeline fail, all threw an error in the autopipeline, which is not ideal. Fixing the issue by throwing the errors individually, in the auto pipeline code.
=> In auto pipeline, throw errors seperately

.github/workflows/tests.yaml, examples/deno/main.ts, pkg/http.test.ts, pkg/http.ts
The http client would sleep event after the last retry, which resulted in the following behavior:
```
failing
sleeping 50
failing
sleeping 135.91409142295225
failing
sleeping 369.4528049465325
failing
sleeping 1004.2768461593834
failing
sleeping 2729.907501657212
failing
sleeping 7420.65795512883
throw
```
now the last sleep is removed. Error is thrown immedietly after the last (5th) retry failure.
=> Remove sleep after the last retry attempt

pkg/commands/exec.test.ts, pkg/commands/exec.ts, pkg/commands/mod.ts, pkg/redis.ts
This PR adds a new method to execute arbitrary Redis commands. This command can be used where a command is defined on the Redis server, but not yet implemented on SDK. (we still work hard to remain compatible with the server). Here's an example use:
```typescript
await redis.exec<number|null>(["MEMORY", "USAGE", dataKey])
redis.exec(["GET", "FOO"])
```
=> DX-1382: Generic EXEC command

.github/workflows/tests.yaml, pkg/commands/hgetall.ts, pkg/commands/hrandfield.ts, pkg/commands/xrange.ts, pkg/commands/xrevrange.ts, platforms/nodejs.ts
It is not a O(1) operation in Node.js (V8 engine). So, custom deserializers that were using it extensively like hgetall was running extremely slow on large payloads.
We are now using plain indexing to achieve the same thing.
=> Don't use Array.shift in custom deserializers

pkg/auto-pipeline.test.ts, pkg/auto-pipeline.ts
excluded some commands that may take a long time from the auto pipeline
=> DX-1839: exclude some commands from auto pipeline

pkg/commands/scan.test.ts, pkg/commands/scan.ts, pkg/redis.test.ts, pkg/redis.ts, pkg/util.ts
This PR introduces the `WITHTYPE` option to the scan command which is usefull for getting the types of the keys without sending seperate `TYPE <key>` commands for each one of them.
```ts
await redis.scan("0", {
withTypes: true
})
// Returns
// [cursor, [{ key: "key1", type: "string" }, { key: "key2", type: "list" }]]
```
=> feat: add withtypes option to the scan command

pkg/http.test.ts, pkg/http.ts, platforms/cloudflare.ts, platforms/nodejs.ts
Currently, there is a signal parameter which accepts an AbortSignal but this has two limitations which make configuring request timeout not feasible:
1. If a request gets timeout, the `signal.aborted` field becomes true, and it stays true in subsequent requests as the object remains the same.
2. When we get a timeout, in the request method of HttpClient, a Response object is created with status 200. So the request method never throws an error. The response is simply null.
Did the following to fix the issue:
- Made it possible to pass an AbortSignal creator function as signal.
- When this is done, we simply throw the error which can be cought like this:
```ts
const redis = new Redis({
url: "***",
token: "***",
signal: () => AbortSignal.timeout(500),
});
try {
const count = await …
```
=> DX-1938: update signal parameter to accept function

pkg/http.ts
Fixed a typo in the JSDoc comment for the `backoff` function parameter.
- Changed "cound" to "count" in pkg/http.ts line 71
=> chore: correct typo 'cound' to 'count' in http.ts comment

pkg/commands/subscribe.test.ts, pkg/commands/subscribe.ts
when the message was a string, we tried to parse which got an error. Also, test durations were too short and we were getting the subscribe event instead of the message event
=> DX-2161: fall back to returning the message string if message is not parsable
